In [21]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import tensorflow
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential


In [3]:
data = load_iris()

X, y = data.data, data.target

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [8]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [22]:
y_train = tensorflow.keras.utils.to_categorical(y_train)
y_test = tensorflow.keras.utils.to_categorical(y_test)

In [23]:
model = Sequential([
    Dense(16, activation='relu', input_shape=(4,)),
    Dense(8, activation='relu'),
    Dense(3, activation='softmax')
])

C:\Users\jacek\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [26]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [27]:
learn = model.fit(
    X_train,
    y_train,
    epochs=100,
    validation_split=0.2,
    batch_size=8
)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.5104 - loss: 0.9933 - val_accuracy: 0.4167 - val_loss: 0.9690
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5521 - loss: 0.9038 - val_accuracy: 0.5000 - val_loss: 0.8773
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5833 - loss: 0.8198 - val_accuracy: 0.6250 - val_loss: 0.8057
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5938 - loss: 0.7563 - val_accuracy: 0.6250 - val_loss: 0.7509
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6458 - loss: 0.7004 - val_accuracy: 0.6667 - val_loss: 0.7090
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6979 - loss: 0.6582 - val_accuracy: 0.6250 - val_loss: 0.6773
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7083 - loss: 0.6236 - val_accuracy: 0.6250 - val_loss: 0.6521
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7083 - loss: 0.5952 - val_accuracy: 0.6250 - 

In [28]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Accuracy:", accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.9667 - loss: 0.0780
Accuracy: 0.9666666388511658


In [30]:
prediction = model.predict(X_test)

print(prediction[:5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
[[9.9942398e-01 5.7550619e-04 6.3098071e-07]
 [2.0518100e-03 1.8673721e-01 8.1121099e-01]
 [2.1222958e-02 9.7640806e-01 2.3689589e-03]
 [9.3719019e-03 9.8847920e-01 2.1488962e-03]
 [9.9981016e-01 1.8958809e-04 2.8404287e-07]]
